[project]
name = "liquidctl-server"
dynamic = ["version"]
description = ""
authors = [{ name = "Antoine Bouteiller" }]
requires-python = ">=3.11,<3.14"
dependencies = ["liquidctl @ git+https://github.com/liquidctl/liquidctl.git@d6568b12f5135d21d609396dbb27fef25c790bd9", "pywin32>=311,<312", "msgspec>=0.20.0,<0.21.0"]

[dependency-groups]
dev = ["ruff>=0.14.0,<0.15.0", "nuitka>=2.5.0,<3.0.0"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "../../.release-please-manifest.json"
pattern = '\{\s*"\."\s*:\s*"(?P<version>[^"]+)"\s*\}'

[tool.hatch.metadata]
allow-direct-references = true